"""empty message

Revision ID: 404ecf411749
Revises: 
Create Date: 2018-08-31 15:30:16.104228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404ecf411749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humoer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=250), nullable=False),
    sa.Column('beskrivelse', sa.String(length=350), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitat', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('barn_id', sa.Integer(), nullable=False),
    sa.Column('humoer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barn_id'], ['barn.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['humoer_id'], ['humoer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitat')
    op.drop_table('humoer')
    op.drop_table('barn')
    # ### end Alembic commands ###
