"""empty message

Revision ID: 8601f82e9053
Revises: 118b0f90b408
Create Date: 2018-09-03 00:03:15.542489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8601f82e9053'
down_revision = '118b0f90b408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitat', sa.Column('info', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitat', 'info')
    # ### end Alembic commands ###
